name: cdk-deployment

on:
  push:
    branches: [ main, develop ]

env:
  AWS_REGION : us-west-2

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Authenticate
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::196736724465:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub-AWS-Federated-OIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install nodejs npm -y
          sudo npm install -g aws-cdk
          npm install
        working-directory: infrastructure
      - name: Synth
        run: |
          cdk synth
        working-directory: infrastructure
      - name: Deploy
        run: |
          cdk deploy --context stackName=Infrastructure-${GITHUB_REF#refs/heads/}
        working-directory: infrastructure